In [1]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, accuracy_score
import os
from ultralytics import YOLO
import numpy as np


In [2]:
ground_truth = {}
classes = {'batteries': 0, 'clothes': 1, 'glass': 2, 'metal': 3, 'organic': 4, 'paper': 5, 'plastic': 6}
model = YOLO("./runs/classify/train17/weights/best.pt")  # Replace with your model path


In [3]:
test_dataset_path = "/home/202490517/waste-classifier/data/test/"
for class_dir in os.listdir(test_dataset_path):
    class_path = os.path.join(test_dataset_path, class_dir)
    if not os.path.isdir(class_path):
        continue
    for img_name in os.listdir(class_path):
        ground_truth[img_name] = classes[class_dir]
y_pred = []
y_true = []

In [4]:
for class_dir in os.listdir(test_dataset_path):
    class_path = os.path.join(test_dataset_path, class_dir)
    if not os.path.isdir(class_path):
        continue
    for img_name in os.listdir(class_path):
        img_path = os.path.join(class_path, img_name)
        # img = cv2.imread(image_path)
        # if img is None:
        #     print(f"Image {img_name} not found.")
        #     continue

        results = model(img_path)
        predicted_label = results[0].probs.top1
        y_true.append(ground_truth[img_name])
        y_pred.append(predicted_label)


image 1/1 /home/202490517/waste-classifier/data/test/plastic/plastic282.jpg: 640x640 plastic 1.00, glass 0.00, paper 0.00, clothes 0.00, batteries 0.00, 22.5ms
Speed: 25.2ms preprocess, 22.5ms inference, 0.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/202490517/waste-classifier/data/test/plastic/plastic252.jpg: 640x640 plastic 0.91, glass 0.07, metal 0.02, paper 0.00, organic 0.00, 22.9ms
Speed: 20.4ms preprocess, 22.9ms inference, 0.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/202490517/waste-classifier/data/test/plastic/plastic362.jpg: 640x640 paper 0.69, plastic 0.30, metal 0.01, clothes 0.00, organic 0.00, 22.9ms
Speed: 15.5ms preprocess, 22.9ms inference, 0.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/202490517/waste-classifier/data/test/plastic/plastic398.jpg: 640x640 plastic 0.59, metal 0.29, glass 0.11, organic 0.00, paper 0.00, 22.9ms
Speed: 15.4ms preprocess, 22.9ms inference, 0.1ms postprocess per image 

In [5]:

y_true = np.array(y_true)
y_pred = np.array(y_pred)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

conf_matrix = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

class_wise_ap = []

Accuracy: 0.84
Precision: 0.85
Recall: 0.84
F1 Score: 0.84
Confusion Matrix:
[[151   3   0   7   5   1  13]
 [  2 104   0   6   1   1   3]
 [  0   0 106   4   0   4  10]
 [  3   0  36 106   1  18  11]
 [  1   1   0   5  92   0   8]
 [  0   0   0   1   0 234   0]
 [  0   1  20   4   0   8 166]]


<Figure size 1200x800 with 0 Axes>

<Figure size 1200x800 with 0 Axes>